{{- if .Values.modules.server.enabled }}
{{- $mod := dict "root" . "name" "server" "component" "server" "module" .Values.modules.server -}}
{{ include "trustification.authenticator.defaultConfigMap" $mod }}
{{- end }}
