{{- if and .Values.modules.server.enabled }}
{{- $mod := dict "root" . "name" "server" "component" "server" "module" .Values.modules.server -}}
{{- include "trustification.application.defaultService" $mod }}
{{- end }}